"""Tests for the `P2-PHASE-01` Fierz verification and branch-depth derivation.

These guard the algebra and the potential reconstruction, not any physical
conclusion. Nothing here asserts that a branch is preferred, or that any
channel is selected.

The potential reference value used below is SELF-GENERATED by this task and
recorded in this task's own results artifact. It is a regression anchor
against future drift; it is NOT a pre-existing frozen number and is NOT
independent validation that the reconstruction is correct.
"""

import json
import sys
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from p2_phase01_fierz_and_depths import (  # noqa: E402
    BASIS_ORDER,
    GRASSMANN_CROSSING_SIGN,
    basis_checks,
    dirac_basis,
    generator_checks,
    induced_coefficients,
    reconstruct_matrix,
)
from p2_phase01_scalar_exploratory import (  # noqa: E402
    WilsonQuadrature,
    first_derivative,
    reconstructed_potential,
)

FREEZE = ROOT / "derivations/P2-CHANNEL-FREEZE-01_phaseA_freeze.md"
FIERZ_JSON = ROOT / "results/P2-CHANNEL-FREEZE/fierz_matrix.json"
RESULTS = (ROOT / "results/P2-PHASE-01/fierz-and-branch-depths"
           / "fierz_and_depths.json")


def _frozen_embedded():
    line = FREEZE.read_text(encoding="utf-8").splitlines()[97]
    return json.loads(line)["matrix_rational"]


def _rat(rows):
    return sp.Matrix(5, 5, lambda i, j: sp.Rational(sp.nsimplify(str(rows[i][j]))))


# ---- Deliverable 2: element-by-element equality --------------------------
def test_reconstruction_equals_frozen_matrix_entry_by_entry():
    """Exact rationals, not numerics and not up to a tolerance."""
    fams, _, _ = dirac_basis()
    m, _ = reconstruct_matrix(fams)
    frozen = _rat(_frozen_embedded())
    for i in range(5):
        for j in range(5):
            assert m[i, j] == frozen[i, j], (
                f"entry [{BASIS_ORDER[i]}][{BASIS_ORDER[j]}] "
                f"reconstructed {m[i, j]} != frozen {frozen[i, j]}"
            )


def test_two_frozen_copies_agree():
    """The freeze's embedded matrix and the standalone JSON must agree."""
    a = _rat(_frozen_embedded())
    b = _rat(json.loads(FIERZ_JSON.read_text(encoding="utf-8"))["matrix_rational"])
    assert a == b


def test_frozen_matrix_carries_no_crossing_sign():
    """Records the observed placement of grassmann_crossing_sign.

    The frozen matrix equals the reconstruction WITHOUT the -1 factor. This
    test locks the observation so a later change of convention cannot pass
    silently; it does not assert which placement is correct.
    """
    fams, _, _ = dirac_basis()
    m, _ = reconstruct_matrix(fams)
    frozen = _rat(_frozen_embedded())
    assert m == frozen
    assert GRASSMANN_CROSSING_SIGN * m == -frozen


# ---- Deliverable 5: completeness, traces, generators ---------------------
def test_sixteen_element_basis_is_complete_and_orthogonal():
    fams, g, g5 = dirac_basis()
    checks = basis_checks(fams, g, g5)
    assert checks["element_count"] == 16
    assert checks["rank_of_span"] == 16
    assert checks["spans_4x4_matrices"]
    assert checks["linearly_independent"]
    assert checks["all_hermitian"]
    assert checks["all_square_to_Id4"]
    assert checks["orthogonality_trace_GaGb_eq_4delta"]
    assert checks["trace_Id4"] == "4"
    for family in BASIS_ORDER:
        assert checks["trace_proportionality_constant_per_family"][family] == "4"


def test_gamma5_is_hermitian_and_squares_to_identity():
    """The PI-ruled definition: gamma(0)gamma(1)gamma(2)gamma(3), no extra I."""
    fams, g, g5 = dirac_basis()
    assert sp.simplify(g5.H - g5) == sp.zeros(4)
    assert sp.simplify(g5 * g5 - sp.eye(4)) == sp.zeros(4)


def test_generator_normalisation_and_completeness():
    out = generator_checks(ns=(2, 3))
    for n, rec in out.items():
        assert rec["generator_count"] == rec["expected_count"]
        assert rec["trace_lamA_lamB_eq_2delta"]
        assert rec[
            "completeness_sum_lamA_ij_lamA_kl_eq_2_delta_il_delta_kj"]
        assert rec["singlet_is_sqrt_2_over_n_times_identity"]


# ---- Deliverable 6: involution as it actually holds ----------------------
def test_involution_holds_for_the_frozen_matrix():
    frozen = _rat(_frozen_embedded())
    residual = sp.simplify(frozen * frozen - sp.eye(5))
    assert residual == sp.zeros(5, 5), f"exact residual: {residual}"
    assert frozen.rank() == 5


def test_involution_does_not_discriminate_the_crossing_sign():
    """Both signed and unsigned forms square to the identity."""
    fams, _, _ = dirac_basis()
    m, _ = reconstruct_matrix(fams)
    assert sp.simplify(m * m - sp.eye(5)) == sp.zeros(5, 5)
    assert sp.simplify((-m) * (-m) - sp.eye(5)) == sp.zeros(5, 5)


# ---- Deliverable 4: the canonical-to-Fierz conversion is locked ----------
def test_pseudoscalar_conversion_sign_is_explicit():
    """An UNCONVERTED (S,P) = (1,1) vector must not reproduce the result."""
    frozen = _rat(_frozen_embedded())
    converted = sp.Matrix([[1, -1, 0, 0, 0]])
    unconverted = sp.Matrix([[1, 1, 0, 0, 0]])
    got = converted * frozen
    bad = unconverted * frozen
    assert got != bad, "conversion must change the induced coefficients"
    # the converted vector carries the explicit minus on P
    assert converted[0, 1] == -converted[0, 0]


def test_induced_coefficients_are_exact_and_split_singlet_traceless():
    frozen = _rat(_frozen_embedded())
    out = induced_coefficients(frozen)
    assert out["converted_vector_in_frozen_basis"]["P"].lstrip().startswith("-")
    for family in BASIS_ORDER:
        assert out["induced_coefficient_traceless"][family] == "0"
    singlet = out["induced_coefficient_singlet"]
    # Every induced coefficient is an exact expression in G; N cancels against
    # the internal completeness factor. Compare symbol NAMES: sympify() builds
    # assumption-free symbols that never equal Symbol("G", positive=True).
    for family in BASIS_ORDER:
        expr = sp.sympify(singlet[family])
        assert {s.name for s in expr.free_symbols} <= {"G"}, singlet[family]
        assert expr.is_rational_function()


# ---- (b): the potential reconstruction ----------------------------------
def test_reconstructed_potential_matches_self_generated_anchor():
    """NONZERO reference value at a stated Mhat != 0 on a stated grid.

    Self-generated regression anchor, not independent validation.
    """
    payload = json.loads(RESULTS.read_text(encoding="utf-8"))
    anchor = payload["derivation_b_branch_depths"]["regression_anchor"]
    assert anchor["mhat"] != 0.0
    assert abs(anchor["potential_minus_trivial"]) > 1.0e-6, (
        "anchor must be nonzero, so an identically-zero implementation fails"
    )
    quad = WilsonQuadrature(n=anchor["n"], shift=anchor["shift"])
    value = reconstructed_potential(anchor["mhat"], anchor["G"], quad)
    assert abs(value - anchor["potential_minus_trivial"]) < 1.0e-10


def test_potential_derivative_reproduces_the_reduced_first_derivative():
    """Independent derivative check, including a stationary and a
    non-stationary point."""
    payload = json.loads(RESULTS.read_text(encoding="utf-8"))
    anchor = payload["derivation_b_branch_depths"]["regression_anchor"]
    quad = WilsonQuadrature(n=anchor["n"], shift=anchor["shift"])
    coupling = anchor["G"]
    h = 1.0e-5
    for mhat in (0.0, 0.5):
        numerical = (
            reconstructed_potential(mhat + h, coupling, quad)
            - reconstructed_potential(mhat - h, coupling, quad)
        ) / (2.0 * h)
        analytic = first_derivative(mhat, coupling, quad)
        assert abs(numerical - analytic) < 1.0e-6, (mhat, numerical, analytic)
    # Mhat = 0 is a stationary point: the derivative must vanish there.
    assert abs(first_derivative(0.0, coupling, quad)) == 0.0
    # Mhat = 0.5 at this coupling is NOT stationary: it must not vanish.
    assert abs(first_derivative(0.5, coupling, quad)) > 1.0e-6


def test_potential_zero_is_reported_as_undetermined():
    payload = json.loads(RESULTS.read_text(encoding="utf-8"))
    block = payload["derivation_b_branch_depths"]
    assert "NOT DEFINED UNDER THE FROZEN MATERIAL" in block["potential_zero"]
    for row in block["rows"][:5]:
        assert row["potential_value"] == "NOT DEFINED UNDER THE FROZEN MATERIAL"


def test_no_decision_is_recorded_in_the_results_artifact():
    payload = json.loads(RESULTS.read_text(encoding="utf-8"))
    taken = payload["decisions_taken"]
    assert taken["hubbard_stratonovich_channel"].startswith("NONE")
    assert taken["vat_orientation_or_components"].startswith("NONE")
    assert taken["potential_zero"].startswith("NONE")
    assert taken["branch_characterisation"].startswith("NONE")
    assert payload["status"].startswith("DERIVATION")
